apiVersion: v1
kind: ConfigMap
metadata:
  name: envconfig
data:
  loglevel: debug 

---
# API Version  
apiVersion: apps/v1
kind: Deployment
# Deployment metadata start
metadata:
  name: busybox-deployment
  labels:
    app: busybox
# Deployment metadata end
# Pod spec start    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
# Pod spec end       
# template start      
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:  
        - name: busybox
          image: busybox       
          command: ["/bin/sh", "-ec", "sleep 1000"] 
          envFrom:
          - configMapRef:
              name: envconfig

# template end
