apiVersion: v1
kind: ConfigMap
metadata:
  name: springbootdemo-demo-configmap
data:
  application.properties: |
    server.port=7777

---

# API Version  
apiVersion: apps/v1
kind: Deployment
# Deployment metadata start
metadata:
  name: springbootdemo-deployment
  labels:
    app: springbootdemo
# Deployment metadata end
# Pod spec start    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdemo
# Pod spec end       
# template start      
  template:
    metadata:
      labels:
        app: springbootdemo
    spec:
      containers:  
        - name: springbootdemo
          image: lianduantraining/springbootdemo:v1
          ports:
          - containerPort: 9999
          volumeMounts: 
          - name: springboot-config
            mountPath: /myMicroservice/application.properties
            subPath: application.properties
      volumes:
        - name: springboot-config
          configMap:
            name: springbootdemo-demo-configmap
          items:
            - key: application.properties
              path: application.properties
# template end